version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube:/opt/sonarqube

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql

volumes:
  sonarqube:
    driver: local
    driver_opts:
      type: none
      device: "D:/docker_volumes/sonarqube"
      o: bind
  sonar_db:
    driver: local
    driver_opts:
      type: none
      device: "D:/docker_volumes/db/sonarqube"
      o: bind