version: '3'

services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    #command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "53:53"
      - "53:53/udp"
      #- "8080:8080"
    volumes:
      - D:/docker_volumes/coredns:/etc/coredns