version: '3'
services:
 db:
   image: mysql:latest
   container_name: mysql
   ports:
     - 3306:3306
   environment:
     - MYSQL_ROOT_PASSWORD=pass1234
     - MYSQL_DATABASE=myDB
   volumes:
     - D:/docker_volumes/db/mysql:/var/lib/mysql