version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=postgres #optional (specify default database instead of $POSTGRES_DB)
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - D:/docker_volumes/db/postgres:/var/lib/postgresql/data